version: "3.3"
    
services:
  server:
    container_name: tuttacatter_server
    build:
      dockerfile: ./server/Dockerfile
      context: .
    environment:
      - DB_HOST=database
      - DB_NAME=product
      - SERVER_PORT=8000
    ports:
      - "8000:8000"
    command: yarn start

  database:
      container_name: tuttacatter_database
      build:
        dockerfile: Dockerfile
        context: ./database

    